sudo: required
services:
    - docker

before_install:
    - docker build -t jessie75919/docker-react -f Dockerfile.dev .

script:
    - docker run jessie75919/docker-react npm run test -- --coverage


    